# site settings
title: COVID19
subtitle: Statistics and Research
email: miquel_oli@me.com
description: This website aims to help increase the publicâ€™s understanding of the evolving COVID-19.
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: null
city: Palma
state: Baleares
zip_code: null
country: Spain
phone: null

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url:  
googleplus_url:  
instagram_url: 
linkedin_url: https://www.linkedin.com/in/miquel-oliver-almi%C3%B1ana-0123a9a2/
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
